### PR TITLE
fix(css) long words in tweets archive

### PR DESCRIPTION
**Pull request by Grawl**

### CODE REVIEW

**Comment by iamstarkov** [comment]
https://twitter.com/GrawlCore/status/683501060007276544

**Comment by Grawl** [comment]
Will you merge it? Do this fails are somehow related to my PR?

**Comment by iamstarkov** [comment]
i updated generator and tests, can you rebase your commits?

**Comment by Grawl** [comment]
I am going sleep right now because of 3:07 on my clock, maybe later.

**Comment by iamstarkov** [comment]
you have forced me 😛

**Comment by Grawl** [comment]
Don't see any reason to squash commits for each PR

**Comment by iamstarkov** [comment]
i was talking not about squashing but about rebasing. because commits order does matter. take a look https://github.com/iamstarkov/generator-underhood/commits/master

**Comment by iamstarkov** [comment]
its wrong now, thats why i will rebase pull-requests on my own in the future

**Comment by Grawl** [comment]
can't get it. what you want to have in result of rebase?

**Comment by iamstarkov** [comment]
proper commits order, i made commit "update tests" before merge pull-request, but commits from pr are _before_ mine commit
screen shot 2016-01-05 at 18 11 57

**Comment by Grawl** [comment]
So what is wrong? Upload time matters too.

**Comment by iamstarkov** [comment]
okay

**Pull request merged**
